#!/bin/sh

# install neovim >= 0.5
sudo add-apt-repository -y ppa:neovim-ppa/unstable
sudo apt install neovim

# copy init.lua
mkdir -p ~/.config/nvim
cp init.lua ~/.config/nvim

# install packer
# https://github.com/wbthomason/packer.nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim